## Матричный метод

In [2]:
import numpy as np

* 18x+7y=8
*   -17x-8y=13

In [3]:
K = np.array([[18., 7.], [-17., -8.]])
K

array([[ 18.,   7.],
       [-17.,  -8.]])

In [4]:
L = np.array([8., 13.])
L

array([ 8., 13.])

In [5]:
np.linalg.solve(K, L)

array([  6.2, -14.8])

Ответ: 6.2, -14.8