## Свойства матричных вычислений

In [2]:
import numpy as np

In [3]:
l = [[14, 20, 54, 5], [87, 5, 2,74], [62, 8, 2, 45], [47, 37, 17, 78]]
A = np.array(l)
A

array([[14, 20, 54,  5],
       [87,  5,  2, 74],
       [62,  8,  2, 45],
       [47, 37, 17, 78]])

In [4]:
k = [[15, 7, 45, 3], [52, 12, 17, 17], [46, 53, 51, 47], [25, 43, 51, 61]]
B = np.array(k)
B

array([[15,  7, 45,  3],
       [52, 12, 17, 17],
       [46, 53, 51, 47],
       [25, 43, 51, 61]])

In [5]:
k = [[81, 24, 24, 4], [54, 58, 87, 87], [8, 78, 54, 69], [8, 31, 5, 6]]
C = np.array(k)
C

array([[81, 24, 24,  4],
       [54, 58, 87, 87],
       [ 8, 78, 54, 69],
       [ 8, 31,  5,  6]])

Транспонирование матрицы:

In [6]:
A.transpose()

array([[14, 87, 62, 47],
       [20,  5,  8, 37],
       [54,  2,  2, 17],
       [ 5, 74, 45, 78]])

In [7]:
A.T

array([[14, 87, 62, 47],
       [20,  5,  8, 37],
       [54,  2,  2, 17],
       [ 5, 74, 45, 78]])

Дважды транспонированная матрица равна исходной матрице:

In [8]:
(A.T).T

array([[14, 20, 54,  5],
       [87,  5,  2, 74],
       [62,  8,  2, 45],
       [47, 37, 17, 78]])

Транспонирование суммы матриц равно сумме транспонированных матриц:

In [9]:
(A+B).T

array([[ 29, 139, 108,  72],
       [ 27,  17,  61,  80],
       [ 99,  19,  53,  68],
       [  8,  91,  92, 139]])

In [10]:
A.T+B.T

array([[ 29, 139, 108,  72],
       [ 27,  17,  61,  80],
       [ 99,  19,  53,  68],
       [  8,  91,  92, 139]])

Транспонирование произведения матриц равно произведению транспонированных
матриц расставленных в обратном порядке:

In [11]:
(A.dot(B)).T

array([[3859, 3507, 2563, 5361],
       [3415, 3957, 2571, 5028],
       [3979, 7876, 5323, 7589],
       [3225, 4954, 3161, 6327]])

In [12]:
(B.T).dot(A.T)

array([[3859, 3507, 2563, 5361],
       [3415, 3957, 2571, 5028],
       [3979, 7876, 5323, 7589],
       [3225, 4954, 3161, 6327]])

Транспонирование произведения матрицы на число равно произведению этого
числа на транспонированную матрицу:

In [13]:
t = 2

In [14]:
(t * A).T

array([[ 28, 174, 124,  94],
       [ 40,  10,  16,  74],
       [108,   4,   4,  34],
       [ 10, 148,  90, 156]])

In [15]:
t * (A.T)

array([[ 28, 174, 124,  94],
       [ 40,  10,  16,  74],
       [108,   4,   4,  34],
       [ 10, 148,  90, 156]])

Определители исходной и транспонированной матрицы совпадают:

In [16]:
format(np.linalg.det(A), '.9g')

'1815340'

In [17]:
format(np.linalg.det(A.T), '.9g')

'1815340'

Умножение матрицы на число


In [19]:
6 * A

array([[ 84, 120, 324,  30],
       [522,  30,  12, 444],
       [372,  48,  12, 270],
       [282, 222, 102, 468]])

Произведение единицы и любой заданной матрицы равно заданной матрице:

In [20]:
7 * A

array([[ 98, 140, 378,  35],
       [609,  35,  14, 518],
       [434,  56,  14, 315],
       [329, 259, 119, 546]])

Произведение нуля и любой матрицы равно нулевой матрице, размерность которой
равна исходной матрицы:

In [27]:
0 * A

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

 Произведение матрицы на сумму чисел равно сумме произведений матрицы на
каждое из этих чисел:

In [21]:
(6 + 5) * A

array([[154, 220, 594,  55],
       [957,  55,  22, 814],
       [682,  88,  22, 495],
       [517, 407, 187, 858]])

In [22]:
8 * A + 6 * A

array([[ 196,  280,  756,   70],
       [1218,   70,   28, 1036],
       [ 868,  112,   28,  630],
       [ 658,  518,  238, 1092]])

Произведение матрицы на произведение двух чисел равно произведению второго
числа и заданной матрицы, умноженному на первое число:

In [23]:
(3 * 3) * A

array([[126, 180, 486,  45],
       [783,  45,  18, 666],
       [558,  72,  18, 405],
       [423, 333, 153, 702]])

In [31]:
2 * (3 * A)

array([[ 66,   6,  36,  12],
       [204,   6,  24,  18],
       [252,  12,  66,  54],
       [ 24,  18,   6, 108]])

Произведение суммы матриц на число равно сумме произведений этих матриц на
заданное число:

In [25]:
3 * (A + B)

array([[ 87,  81, 297,  24],
       [417,  51,  57, 273],
       [324, 183, 159, 276],
       [216, 240, 204, 417]])

In [26]:
2 * A + 2 * B

array([[ 58,  54, 198,  16],
       [278,  34,  38, 182],
       [216, 122, 106, 184],
       [144, 160, 136, 278]])

Сложение матриц


In [27]:
A + B

array([[ 29,  27,  99,   8],
       [139,  17,  19,  91],
       [108,  61,  53,  92],
       [ 72,  80,  68, 139]])

In [28]:
B + A

array([[ 29,  27,  99,   8],
       [139,  17,  19,  91],
       [108,  61,  53,  92],
       [ 72,  80,  68, 139]])

In [29]:
A + (B + C)

array([[110,  51, 123,  12],
       [193,  75, 106, 178],
       [116, 139, 107, 161],
       [ 80, 111,  73, 145]])

In [30]:
(A + B) + C

array([[110,  51, 123,  12],
       [193,  75, 106, 178],
       [116, 139, 107, 161],
       [ 80, 111,  73, 145]])

In [31]:
A + (-1)*A

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

Диаграмма матричного умножения


In [32]:
A.dot(B)

array([[3859, 3415, 3979, 3225],
       [3507, 3957, 7876, 4954],
       [2563, 2571, 5323, 3161],
       [5361, 5028, 7589, 6327]])

Ассоциативность умножения. Результат умножения матриц не зависит от порядка, в
котором будет выполняться эта операция:

In [33]:
A.dot(B.dot(C))

array([[ 554621,  701023,  620712,  606442],
       [ 600385, 1081576,  878501,  931455],
       [ 414309,  723815,  588436,  620182],
       [ 817081, 1208367, 1007541, 1020483]])

In [34]:
(A.dot(B)).dot(C)

array([[ 554621,  701023,  620712,  606442],
       [ 600385, 1081576,  878501,  931455],
       [ 414309,  723815,  588436,  620182],
       [ 817081, 1208367, 1007541, 1020483]])

Дистрибутивность умножения. Произведение матрицы на сумму матриц равно
сумме произведений матриц:

In [35]:
A.dot(B+C)

array([[ 6545,  9278,  8996,  8777],
       [11432,  8785, 10877,  6319],
       [ 8393,  6074,  7840,  4513],
       [11926, 12046, 13244, 11375]])

In [36]:
A.dot(B)+A.dot(C)

array([[ 6545,  9278,  8996,  8777],
       [11432,  8785, 10877,  6319],
       [ 8393,  6074,  7840,  4513],
       [11926, 12046, 13244, 11375]])

Умножение матриц в общем виде не коммутативно. Это означает, что для матриц не
выполняется правило независимости произведения от перестановки множителей:

In [37]:
A.dot(B)

array([[3859, 3415, 3979, 3225],
       [3507, 3957, 7876, 4954],
       [2563, 2571, 5323, 3161],
       [5361, 5028, 7589, 6327]])

In [38]:
B.dot(A)

array([[ 3750,   806,   965,  2852],
       [ 3625,  1865,  3155,  3239],
       [10626,  3332,  3491, 10113],
       [10120,  3380,  2575, 10360]])

Произведение заданной матрицы на единичную равно исходной матрице:

In [39]:
E = np.matrix('1 0 0 0; 0 1 0 0; 0 0 1 0; 0 0 0 1')
E.dot(A)

matrix([[14, 20, 54,  5],
        [87,  5,  2, 74],
        [62,  8,  2, 45],
        [47, 37, 17, 78]])

In [40]:
A.dot(E)

matrix([[14, 20, 54,  5],
        [87,  5,  2, 74],
        [62,  8,  2, 45],
        [47, 37, 17, 78]])

Произведение заданной матрицы на нулевую матрицу равно нулевой матрице:

In [41]:
Z = np.matrix('0 0 0 0; 0 0 0 0; 0 0 0 0; 0 0 0 0')
Z.dot(A)

matrix([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [42]:
A.dot(Z)

matrix([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

Определитель матрицы

In [43]:
np.linalg.det(A)

1815339.9999999984

Определитель матрицы остается неизменным при ее транспонировании:

In [44]:
round(np.linalg.det(A), 3)

1815340.0

In [45]:
round(np.linalg.det(A.T), 3)

1815340.0

Если у матрицы есть строка или столбец, состоящие из нулей, то определитель
такой матрицы равен нулю:

In [46]:
N = np.matrix('1 1 1; 0 0 1; 2 2 1')
np.linalg.det(N)

-2.0

При перестановке строк матрицы знак ее определителя меняется на
противоположный:

In [47]:
N = np.matrix('2 5 4; 7 4 0; 54 12 1')
round(np.linalg.det(N), 3)

-877.0

In [50]:
N = np.matrix('1 22 12; 1 1 1; 11 18 2')
round(np.linalg.det(N), 3)

266.0

Если у матрицы есть две одинаковые строки, то ее определитель равен нулю:

In [52]:
N = np.matrix('1 1 1; 2 1 5; 1 1 1')
np.linalg.det(N)

0.0

Если все элементы строки или столбца матрицы умножить на какое-то число, то и
определитель будет умножен на это число:

In [53]:
N = np.matrix('1 1 1; 7 1 6; 8 16 32')
k = 2
M = N.copy()
M[2, :] = k * M[2, :]
print(M)

[[ 1  1  1]
 [ 7  1  6]
 [16 32 64]]


In [54]:
det_N = round(np.linalg.det(N), 3)
det_M = round(np.linalg.det(M), 3)

In [55]:
det_N * k

-272.0

In [56]:
det_M

-272.0

Если все элементы строки или столбца можно представить как сумму двух
слагаемых, то определитель такой матрицы равен сумме определителей двух соответствующих
матриц:

In [58]:
C = A.copy()
C[1, :] += B[1, :]
print(C)

[[ 14  20  54   5]
 [139  17  19  91]
 [ 62   8   2  45]
 [ 47  37  17  78]]


In [59]:
A

array([[14, 20, 54,  5],
       [87,  5,  2, 74],
       [62,  8,  2, 45],
       [47, 37, 17, 78]])

In [60]:
B

array([[15,  7, 45,  3],
       [52, 12, 17, 17],
       [46, 53, 51, 47],
       [25, 43, 51, 61]])

In [61]:
round(np.linalg.det(C), 3)

160480.0

In [62]:
round(np.linalg.det(A), 3) + round(np.linalg.det(B), 3)

3952172.0

Если к элементам одной строки прибавить элементы другой строки, умноженные на
одно и тоже число, то определитель матрицы не изменится:

In [63]:
C = A.copy()
C[1, :] = C[1, :] + 2 * C[0, :]
A

array([[14, 20, 54,  5],
       [87,  5,  2, 74],
       [62,  8,  2, 45],
       [47, 37, 17, 78]])

In [64]:
C

array([[ 14,  20,  54,   5],
       [115,  45, 110,  84],
       [ 62,   8,   2,  45],
       [ 47,  37,  17,  78]])

In [65]:
round(np.linalg.det(A), 3)

1815340.0

In [66]:
round(np.linalg.det(C), 3)

1815340.0

Если строка или столбец матрицы является линейной комбинацией других строк
(столбцов), то определитель такой матрицы равен нулю:

In [67]:
A[1, :] = A[0, :] + 2 * A[2, :]
round(np.linalg.det(A), 3)

-0.0

Если матрица содержит пропорциональные строки, то ее определитель равен нулю:

In [68]:
A[1, :] = 2 * A[0, :]
A

array([[ 14,  20,  54,   5],
       [ 28,  40, 108,  10],
       [ 62,   8,   2,  45],
       [ 47,  37,  17,  78]])

In [69]:
round(np.linalg.det(A), 3)

0.0

Обратная матрица

Обратная матрица обратной матрицы есть исходная матрица:

In [70]:
N = np.matrix('1 3; -1 4')
np.linalg.inv(N)

matrix([[ 0.57142857, -0.42857143],
        [ 0.14285714,  0.14285714]])

Обратная матрица транспонированной матрицы равна транспонированной матрице
от обратной матрицы:

In [71]:
np.linalg.inv(N.T)

matrix([[ 0.57142857,  0.14285714],
        [-0.42857143,  0.14285714]])

In [72]:
(np.linalg.inv(N)).T

matrix([[ 0.57142857,  0.14285714],
        [-0.42857143,  0.14285714]])

Обратная матрица произведения матриц равна произведению обратных матриц:

In [73]:
M = np.matrix('1. 8.; 2. 17.')
N = np.matrix('-4. 1.; 3. -9.')
np.linalg.inv(M.dot(N))

matrix([[-4.57575758,  2.15151515],
        [-1.3030303 ,  0.60606061]])

In [74]:
np.linalg.inv(N).dot(np.linalg.inv(M))

matrix([[-4.57575758,  2.15151515],
        [-1.3030303 ,  0.60606061]])